import type { Track } from "./types";

export const mockTracks: Track[] = [
  { id: "t001", artist: "Anyma", title: "Pictures Of You", bpm: 126, key: "8A", genre: "Melodic Techno", energy: 9 },
  { id: "t002", artist: "CamelPhat", title: "Hope", bpm: 124, key: "8A", genre: "Progressive House", energy: 8 },
  { id: "t003", artist: "ARTBAT", title: "Horizon", bpm: 126, key: "8B", genre: "Melodic Techno", energy: 9 },
  { id: "t004", artist: "Monolink", title: "Return To Oz", bpm: 123, key: "7A", genre: "Deep House", energy: 7 },
  { id: "t005", artist: "Ben Böhmer", title: "Beyond Beliefs", bpm: 122, key: "9A", genre: "Organic House", energy: 7 },
  { id: "t006", artist: "Tinlicker", title: "Because You Move Me", bpm: 124, key: "10A", genre: "Progressive House", energy: 8 },
  { id: "t007", artist: "Lane 8", title: "Fingerprint", bpm: 122, key: "6A", genre: "Deep Progressive", energy: 6 },
  { id: "t008", artist: "Yotto", title: "The One You Left Behind", bpm: 123, key: "6B", genre: "Progressive House", energy: 7 },
  { id: "t009", artist: "Boris Brejcha", title: "Gravity", bpm: 125, key: "5A", genre: "High-Tech Minimal", energy: 8 },
  { id: "t010", artist: "Stephan Bodzin", title: "Singularity", bpm: 126, key: "4A", genre: "Melodic Techno", energy: 9 },
  { id: "t011", artist: "Tale Of Us", title: "Nova", bpm: 124, key: "3A", genre: "Melodic Techno", energy: 8 },
  { id: "t012", artist: "Adriatique", title: "Home", bpm: 120, key: "2A", genre: "Deep Techno", energy: 7 },
  { id: "t013", artist: "Mind Against", title: "Dreamcast", bpm: 123, key: "1A", genre: "Melodic Techno", energy: 8 },
  { id: "t014", artist: "Kevin de Vries", title: "Dance With Me", bpm: 128, key: "12A", genre: "Peak Time Techno", energy: 10 },
  { id: "t015", artist: "Charlotte de Witte", title: "Doppler", bpm: 132, key: "11A", genre: "Techno", energy: 10 },
  { id: "t016", artist: "Amelie Lens", title: "Higher", bpm: 134, key: "10B", genre: "Techno", energy: 10 },
  { id: "t017", artist: "Reinier Zonneveld", title: "Things We Might Have Said", bpm: 130, key: "9B", genre: "Acid Techno", energy: 9 },
  { id: "t018", artist: "Solomun", title: "Kackvogel", bpm: 120, key: "8B", genre: "House", energy: 7 },
  { id: "t019", artist: "Maceo Plex", title: "Solar Detroit", bpm: 122, key: "7B", genre: "Electronica", energy: 8 },
  { id: "t020", artist: "Kölsch", title: "Grey", bpm: 126, key: "6B", genre: "Melodic House", energy: 8 },
  { id: "t021", artist: "RÜFÜS DU SOL", title: "Innerbloom", bpm: 122, key: "5B", genre: "Indie Dance", energy: 6 },
  { id: "t022", artist: "Bob Moses", title: "Love Brand New", bpm: 121, key: "4B", genre: "Indie Dance", energy: 7 },
  { id: "t023", artist: "Disclosure", title: "Latch", bpm: 122, key: "3B", genre: "UK Garage", energy: 8 },
  { id: "t024", artist: "Bicep", title: "Glue", bpm: 129, key: "2B", genre: "Breaks", energy: 8 },
  { id: "t025", artist: "Overmono", title: "So U Kno", bpm: 134, key: "1B", genre: "Breakbeat", energy: 9 },
  { id: "t026", artist: "Fred again..", title: "Marea", bpm: 130, key: "12B", genre: "Future Garage", energy: 9 },
  { id: "t027", artist: "Jamie xx", title: "Gosh", bpm: 125, key: "11B", genre: "Electronica", energy: 8 },
  { id: "t028", artist: "Floating Points", title: "LesAlpx", bpm: 128, key: "10A", genre: "Leftfield House", energy: 8 },
  { id: "t029", artist: "Caribou", title: "Never Come Back", bpm: 127, key: "9A", genre: "Indie Electronic", energy: 8 },
  { id: "t030", artist: "Four Tet", title: "Baby", bpm: 126, key: "8A", genre: "Electronica", energy: 7 },
  { id: "t031", artist: "Bonobo", title: "Kerala", bpm: 118, key: "7A", genre: "Downtempo", energy: 6 },
  { id: "t032", artist: "Jon Hopkins", title: "Open Eye Signal", bpm: 128, key: "6A", genre: "Electronica", energy: 9 },
  { id: "t033", artist: "Orbital", title: "Belfast", bpm: 120, key: "5A", genre: "Classic Rave", energy: 7 },
  { id: "t034", artist: "Underworld", title: "Two Months Off", bpm: 130, key: "4A", genre: "Progressive Breaks", energy: 9 },
  { id: "t035", artist: "The Chemical Brothers", title: "Star Guitar", bpm: 127, key: "3A", genre: "Big Beat", energy: 8 },
  { id: "t036", artist: "Daft Punk", title: "Digital Love", bpm: 125, key: "2A", genre: "French House", energy: 7 },
  { id: "t037", artist: "Justice", title: "D.A.N.C.E.", bpm: 113, key: "1A", genre: "Electro House", energy: 8 },
  { id: "t038", artist: "Purple Disco Machine", title: "Body Funk", bpm: 122, key: "12A", genre: "Nu Disco", energy: 8 },
  { id: "t039", artist: "Folamour", title: "These Are Just Places To Me Now", bpm: 121, key: "11A", genre: "Disco House", energy: 7 },
  { id: "t040", artist: "Peggy Gou", title: "It Makes You Forget", bpm: 124, key: "10B", genre: "House", energy: 8 },
  { id: "t041", artist: "Mall Grab", title: "Liverpool Street In The Rain", bpm: 128, key: "9B", genre: "Lo-Fi House", energy: 7 },
  { id: "t042", artist: "DJ Seinfeld", title: "U", bpm: 126, key: "8B", genre: "Lo-Fi House", energy: 7 },
  { id: "t043", artist: "Ross From Friends", title: "Talk To Me You'll Understand", bpm: 125, key: "7B", genre: "Lo-Fi House", energy: 7 },
  { id: "t044", artist: "Sasha", title: "Xpander", bpm: 130, key: "6B", genre: "Progressive Trance", energy: 9 },
  { id: "t045", artist: "Pryda", title: "Opus", bpm: 126, key: "5B", genre: "Progressive House", energy: 9 },
  { id: "t046", artist: "deadmau5", title: "Strobe", bpm: 128, key: "4B", genre: "Progressive House", energy: 9 },
  { id: "t047", artist: "Eric Prydz", title: "Generate", bpm: 126, key: "3B", genre: "Progressive House", energy: 8 },
  { id: "t048", artist: "Above & Beyond", title: "Sun & Moon", bpm: 132, key: "2B", genre: "Trance", energy: 10 },
  { id: "t049", artist: "Armin van Buuren", title: "This Is What It Feels Like", bpm: 130, key: "1B", genre: "Trance", energy: 9 },
  { id: "t050", artist: "Nora En Pure", title: "Come With Me", bpm: 122, key: "12B", genre: "Deep House", energy: 7 },
  { id: "t051", artist: "Elderbrook", title: "Numb", bpm: 120, key: "8A", genre: "Deep House", energy: 6 },
  { id: "t052", artist: "WhoMadeWho", title: "Abu Simbel", bpm: 123, key: "8B", genre: "Indie Dance", energy: 7 },
  { id: "t053", artist: "Booka Shade", title: "Body Language", bpm: 124, key: "9A", genre: "Minimal House", energy: 8 },
  { id: "t054", artist: "Gui Boratto", title: "Beautiful Life", bpm: 125, key: "7A", genre: "Progressive House", energy: 8 },
  { id: "t055", artist: "Sébastien Léger", title: "Lanarka", bpm: 122, key: "8A", genre: "Organic House", energy: 7 },
  { id: "t056", artist: "Massano", title: "The Feeling", bpm: 126, key: "10A", genre: "Melodic Techno", energy: 9 }
];
